### ISSUE TITLE
Is there an api for the images?

### ISSUE THREAD

**Issue by hadees** [DataUSA/datausa-api#2]
I'd like to use your location photos in a project I'm working on.

**Comment by jspeis** [comment]
Hi hadees,

You can use the attribute API to get images by attribute ID:

for example to get the image of Massachusetts* you would use
http://api.datausa.io/attrs/geo/04000US25

Here you can see the image and CC attribution information we use for the image for Massachusetts. You can also just get all of our location attribute data at once by going to http://api.datausa.io/attrs/geo

Does that help?

*if you need help finding the codes you can use our search API http://api.datausa.io/attrs/search/?q=massachusetts
