### ISSUE TITLE
error with pums.yc table

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-api#21]
I'm getting geo attributes returned from this query,because it's not able to find "num_ppl_rca" in the yc table: https://sunbird-api.datausa.io/api/?show=cip&required=avg_wage,num_ppl_rca&sumlevel=all&year=latest

...how difficult is it to add rca values to that table?

**Comment by jspeis** [comment]
We wouldn't have an RCA value for a yc table since that would be a simple share percentage instead of an RCA.

**Comment by davelandry** [comment]
Oops, make sense!
