### ISSUE TITLE
location "05000US99999" on maps

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-api#23]
@davelandry commented on [Fri Apr 28 2017](https://github.com/DataUSA/datausa-site/issues/550)

### Expected Behavior
All locations should have names.

### Current Behavior
There is a weird "05000US99999" location visible on the map when looking at data from the Dartmouth Atlas. @jspeis do you know what this is? Should we be filtering this out of the data calls?

### Steps to Reproduce (for bugs)
https://sunbird.datausa.io/map/?level=county&key=total_medicare_enrollees

### Your Environment

* Browser Name: N/A
* Operating System and Version: N/A

**Comment by jspeis** [comment]
It turned out 05000US99999 is actually the United States (01000US). This has been updated in the database.
