### ISSUE TITLE
Broken queries

### ISSUE THREAD

**Issue by lecy** [DataUSA/datausa-api#3]
The examples at the bottom of the BLS page are broken:

https://github.com/DataUSA/datausa-api/wiki/BLS-API

Examples

http://api.datausa.io/api/?show=naics&sumlevel=all&naics=111&required=emp_2012_thousands
http://api.datausa.io/api/?show=soc&sumlevel=all&soc=110000&required=emp_2012_thousands

**Comment by jspeis** [comment]
@lecy thanks for reporting this issue, when initially writing the documentation we had been using an older (now outdated) version of the BLS projection data from 2012, but we we released the BLS projections data on profile we used newer 2014 based projections. The docs have now been updated accordingly (just changed 20X2 -> 20X4, e.g. emp_2012_thousands now is emp_2014_thousands)

**Comment by lecy** [comment]
Nice response time - thanks!
