### ISSUE TITLE
broken SOC page from BLS growth ids

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-api#30]
The top occupation in [this chart](https://datausa.io/profile/naics/722Z/growth/changing_occs/) has an id of `311000`, which when appearing as text links to this page: https://datausa.io/profile/soc/311000/ ... which gets a 404!

It seems that the id _should_ be `311010` and link to this page? https://datausa.io/profile/soc/311010/

**Comment by jspeis** [comment]
this is now fixed in the university branch
