### ISSUE TITLE
university branch ipeds.gradspct_ycu table has null year values

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-api#45]
as seen in [this](https://university-api.datausa.io/api/years/) API call:

```json
...
"ipeds.gradspct_ycu": [null, 2015, 2014]
...
```

this is currently breaking the CIP profile pages. I can put a filter on the front-end to remove the `null` values, but thought this might be a data bug as well

**Comment by jspeis** [comment]
`gradspct_ycu` is a materialized view that is computed based off the values in other tables and basically that view just needed to be refreshed after the carnegie rollup values were added so now the gradspct_ycu should appear as expected
