### ISSUE TITLE
Hi. I have a question.

### ISSUE THREAD

**Issue by SethConnell** [DataUSA/datausa-api#54]
Does this API have a way to filter through all 50 states by order of name or alphabet, delivering only one result per state?

**Comment by davelandry** [comment]
Hi @SethConnell! We currently only have filters setup based on state ID, like such: https://api.datausa.io/api/?show=geo&required=pop&sumlevel=state&year=all&geo=04000US25

This could be combined with a call from the attribute table to sort the IDs by their display name: https://api.datausa.io/attrs/geo/?sumlevel=state
