### ISSUE TITLE
IPEDS Enrollment wiki outdated

### ISSUE THREAD

**Issue by jdbarillas** [DataUSA/datausa-api#56]
First, thank you for the work you're doing! It truly is remarkable what you've accomplished.

I'm currently trying to run a query for the enrollments from the IPEDS dataset. However, it returns `{"error": "No tables can match the specified query."}`

This is the query I'm currently using:

https://api.datausa.io/api/?show=university&sumlevel=all&year=latest&required=enrolled_total

Any help would be greatly appreciated!

**Comment by davelandry** [comment]
@jdbarillas it looks like the wiki for those columns are out of date. this query worked for me: https://api.datausa.io/api/?show=university&sumlevel=all&year=latest&required=num_enrolled
