### ISSUE TITLE
remove image_path from attribute results

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-api#6]
Kicking Horse!

The attr call: https://api.datausa.io/attrs/geo/16000US3040580/

Returns the state image_path, but it has a beautiful image: https://datausa.io/profile/geo/16000US3040580/

**Comment by jspeis** [comment]
image_path is an outdated field because the image path can now be derived without storage in the database.

To retrieve the image for an attribute you can use https://datausa.io/profile/<attr kind>/<attr id>/img

https://datausa.io/profile/geo/16000US3040580/img

**Comment by davelandry** [comment]
@jspeis the only place that image_path is currently used is with the homepage tiles. I'm not removing it yet, because we call in the smaller thumbnail images for those. Does this endpoint support sending the smaller thumbnails?

**Comment by jspeis** [comment]
right now you could get the thumbnail through the search endpoint https://datausa.io/search/geo/16000US3040580/img but we can also add an option to the profile endpoint like ?mode=splash

**Comment by davelandry** [comment]
I'm fine with using the search endpoint, just didn't know it existed :-)

**Comment by davelandry** [comment]
@jspeis I've removed the last usage of "image_path" from [datausa-site](https://github.com/DataUSA/datausa-site/), so we can rip this out of the API whenever you want 😁
