### ISSUE TITLE
Access ACS Data via API

### ISSUE THREAD

**Issue by ford-scoop** [DataUSA/datausa-api#61]
Hello - I'm trying to access the ACS data (such as this [commute means info](https://datausa.io/api/data?measure=Commute%20Means,Commute%20Means%20Moe&geo=16000US0667000&drilldowns=Group&year=latest)), but it doesn't appear to be available via the DataUSA API. I have tried to make requests using Python's requests library, but either get a 404 response or (after adding headers to the call) get a bunch of uninterpretable hex.

Is it possible to pull down this data using the API? This is one of the calls I tried:

```requests.get("http://banana.datausa.io/api/data?measure=Average Commute Time&drilldowns=Place", headers=headers)```

I also tried putting the parameters in a dictionary and passing them that way.

I am using python 3.6.9 and requests 2.23

**Comment by davelandry** [comment]
Hmm... that data call works for me? Even directly in the browser (with no additional headers) I can see the JSON payload:

<img width="747" alt="Screen Shot 2020-07-28 at 6 06 52 PM" src="https://user-images.githubusercontent.com/1847581/88727200-1f616000-d0fd-11ea-9675-d34f3583f761.png">

The two issues that I could see are:
- you are using `http` instead of `https`
- you should remove the `banana` sub-domain, to ensure that you're always getting the production data (and it will work if we rename the server)

**Comment by ford-scoop** [comment]
Hey! Thank you for the response. Sorry, I was not clear. I _can_ see the JSON payload in the browser, but I _cannot_ when I try to access it via Python. 

I tried replicating what is in the [Python instructions](https://github.com/DataUSA/datausa-api/wiki/Getting-Started#python) for getting started with the API, but with the URL I used above in place of the one in the docs. I get the 403 status code and no JSON payload after making the following call with Python.

```requests.get("https://datausa.io/api/data?measure=Average Commute Time&drilldowns=Place", headers=headers)```

Is that endpoint open on the API for it to be accessed in this way with Python?

**Comment by innerstage** [comment]
Hey! We're working on a proxy issue that prevents Python to query the API on the latest production server. We'll let you know when it's fixed and share a Python example. Thanks for pointing this out!

**Comment by innerstage** [comment]
The issue should be fixed now... here's an example code that I tested locally to get the data in tidy format on a CSV file:

```
import requests
import csv
import pandas as pd


url = "https://datausa.io/api/data?measure=Average Commute Time&drilldowns=Place"
json = requests.get(url).json() # Gets URL and transforms JSON payload to a Python dictionary

df = pd.DataFrame(json["data"]) # Transforms data dictionary into a tidy DataFrame
df.to_csv("result.csv", index=False, quoting=csv.QUOTE_NONNUMERIC) # Saves it as a CSV file
```

**Comment by ford-scoop** [comment]
Thanks @innerstage ! That fix works for me, too. Appreciate the help and responsiveness y'all!

**Comment by Denko** [comment]
Just lurking. Thanks for the code. It works perfectly and I'm inspired to
build on it.
