### ISSUE TITLE
Reference this documentation within datausa.io/about/api/

### ISSUE THREAD

**Issue by pastrylife** [DataUSA/datausa-api#74]
The documentation here is not currently referenced anywhere within the "API" page at https://datausa.io/about/api/

Adding a link to that and the Introduction article (on Medium) would be most helpful for anyone hoping to make use of the API.

**Comment by davelandry** [comment]
@pastrylife First off, my apologies for the current state of the API documentation. Our back-end has been in flux for a little while now, and we hope to have better resources in the near future. This repo (and any documentation about it) is actually completely deprecated and not running anymore, so I've went around and placed warning messages in all of the resources about it and will be archiving this repository.

As a sort of "current state of the API", we understand that the main API documentation page is very sparse ([https://datausa.io/about/api/](https://datausa.io/about/api/)), but it is the most accurate description of the current API. As a first step to understanding it, all of the visualizations on the site feature a "View Data" button, which will show the API url used to generate the visualization:
​​
<img width="1208" alt="112054634-304b5f80-8b2c-11eb-9d82-c6ead0165507" src="https://user-images.githubusercontent.com/1847581/151840250-585b9c9c-f81d-4759-9570-8f3233cfbb01.png">

If you have programming experience and want the most comprehensive picture of what's available (it's a lot), the following endpoint contains a JSON result with a list of every available measure and their drilldowns (along with some other behind the scenes stuff): https://datausa.io/api/cubes
